name: Github Actions Resonate Contacts

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  DevelopmentDeployment:
    runs-on: ubuntu-latest
    environment: develop
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Use node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependencies & Packages
        run: npm install

      - name: Build Files
        run: CI=false NODE_OPTIONS=--max_old_space_size=4096 npm run build --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build files to S3
        run: aws s3 sync build/ s3://${{secrets.S3_BUCKET}}/  --acl public-read

      # - name: Invalidate Cache in Cloudfront for Vishcorp-Dev
      #   run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_VISHCORP}} --paths "/*"

      # : ${{secrets.S3_DEPLOYMENT_ROLE_DEV}}
      #  : ${{secrets.AWS_REGION}}
